networks:
  jenkins-net:
    driver: bridge

services:
  jenkins-master:
    image: jenkins/jenkins:lts-alpine
    container_name: jenkins-master
    ports:
      - "8282:8080"  
      - "50000:50000" 
    volumes:
      - jenkins_master_data:/var/jenkins_home
    networks:
      - jenkins-net
    restart: unless-stopped

  jenkins-agent:
    image: jenkins/inbound-agent:alpine
    container_name: jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_SECRET=fbc6cafd6b9adc3922f0b62e9fbcb289f416f4239b0d34314bb8d44293384c85
      - JENKINS_AGENT_NAME=linux-agent-node
    networks:
      - jenkins-net
    depends_on:
      - jenkins-master
    restart: on-failure
volumes:
  jenkins_master_data:
